version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    env_file:
      - .env
    volumes:
      - db-data:/code/data
  frontend:
    build:
      context: ./interface  
      dockerfile: Dockerfile  
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  db-data:
    driver: local